# FROM node:20-alpine
# WORKDIR /app
# COPY  package.json ./
# RUN npm install
# COPY . .

# RUN npm run build

# FROM nginx:alpine
# COPY --from=0 /app/build /usr/share/nginx/html
# EXPOSE 3000

# CMD [ "nginx", '-g', 'daemon off;' ]
FROM node:20-alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

CMD [ "npm", "run", "dev" ]
