# Generated by Django 4.2.6 on 2023-12-09 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_nickname_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nick', max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Nickname cannot be empty.')]),
        ),
    ]
