# Generated by Django 4.2.5 on 2024-01-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_chattopic_direct_directmessage_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='chat_with',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='replied_to',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Direct',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
