# Generated by Django 4.2.5 on 2024-02-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_directmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text_content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='text_content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='text_content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
