# Generated by Django 4.2.5 on 2024-02-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_text_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='photo',
            field=models.ImageField(default='defaults/default_chat_image.jpg', upload_to='chat/chat_images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='chat/message_images/'),
        ),
        migrations.AlterField(
            model_name='chattopic',
            name='photo',
            field=models.ImageField(default='defaults/default_topic_image.jpg', upload_to='chat/topic_images/'),
        ),
        migrations.AlterField(
            model_name='direct',
            name='photo',
            field=models.ImageField(default='defaults/default_chat_image.jpg', upload_to='chat/chat_images/'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='chat/message_images/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='defaults/default_chat_image.jpg', upload_to='chat/chat_images/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='chat/message_images/'),
        ),
    ]
