# Generated by Django 4.2.5 on 2023-12-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chattopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.chattopic'),
        ),
    ]
