# Generated by Django 4.2.5 on 2024-02-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_photo_alter_chatmessage_image_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='photo',
            field=models.ImageField(default='defaults/default_chat_image.jpg', max_length=255, upload_to='chat/chat_images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image_content',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='chat/message_images/'),
        ),
        migrations.AlterField(
            model_name='direct',
            name='photo',
            field=models.ImageField(default='defaults/default_chat_image.jpg', max_length=255, upload_to='chat/chat_images/'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='image_content',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='chat/message_images/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='defaults/default_chat_image.jpg', max_length=255, upload_to='chat/chat_images/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='image_content',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='chat/message_images/'),
        ),
    ]
