# Generated by Django 4.2.5 on 2023-12-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chat_topic_chat_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.chattopic'),
        ),
    ]
