# Generated by Django 4.2.5 on 2024-01-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_message_replied_to_photomessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="content",
        ),
        migrations.AddField(
            model_name="message",
            name="image_content",
            field=models.ImageField(blank=True, null=True, upload_to="message_images/"),
        ),
        migrations.AddField(
            model_name="message",
            name="text_content",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="PhotoMessage",
        ),
    ]
