# Generated by Django 4.2.5 on 2024-01-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_message_content_message_image_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='photo',
            field=models.ImageField(default='media/defaults/default_chat_image.jpg', upload_to='media/chat/chat_images/'),
        ),
        migrations.AddField(
            model_name='chattopic',
            name='photo',
            field=models.ImageField(default='media/defaults/default_topic_image.jpg', upload_to='media/chat/topic_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='media/chat/message_images/'),
        ),
    ]
