# Generated by Django 4.2.5 on 2024-01-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chat_photo_chattopic_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='max_users',
            field=models.IntegerField(default=0),
        ),
    ]
