# Generated by Django 4.2.5 on 2024-01-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chat_max_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='max_users',
            field=models.IntegerField(default=99),
        ),
    ]
