# Generated by Django 4.2.5 on 2024-01-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chat_max_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.CharField(default='There is no description :(', max_length=255),
        ),
    ]
