# Generated by Django 4.2.5 on 2024-01-11 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0015_basemessage_chatmessage_directmessage_groupmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='There is no description :(', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(default='media/defaults/default_chat_image.jpg', upload_to='media/chat/chat_images/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='users',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('basechat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.basechat')),
            ],
            bases=('chat.basechat',),
        ),
        migrations.AddField(
            model_name='chat',
            name='basechat_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.basechat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.group'),
            preserve_default=False,
        ),
    ]
